### ISSUE TITLE
Omitting specific images

### ISSUE THREAD

**Issue by aladagemre** [todvora/gitbook-plugin-image-captions#14]
Many people might have images (like Chat on gitter.im button) on README, which is not really in the book. Plugin processes README file as well and wraps images with figure and figcaption tags, produces something like:

`<figure id="fig1.1.1"><figcaption class="left">Image 1.1: Join the Chat`https://gitter.im/user/project</figcaption></figure>``

This breaks Gitbook (but not github) description page. I think omitting README file or giving the option to omit some sections would be nice.

**Comment by markomanninen** [comment]
Can you see if this works for you?

`
  "pluginsConfig": {
    "image-captions": {
      "images": {
        "1.2.2": {
          "skip": true
        }
      }
    }
  }
`

**Comment by aladagemre** [comment]
Unfortunately it didn't work. I tried 1.1.1 and 1.2.2 in the snippet you provided, none of them worked.

**Comment by todvora** [comment]
That's because it hasn't been released yet :-) 

I released just now the `3.0.0` version with this feature included. @aladagemre could you please try it now (in the way Marko suggested)?

Thanks!

**Comment by aladagemre** [comment]
Thanks for the update! It's properly working now! Thanks for you efforts! 👍 
`"pluginsConfig": { "image-captions": { "images": { "1.1.1": { "skip": true } } } }`

**Comment by todvora** [comment]
Hi @aladagemre,
Super, I am glad I could help.

@markomanninen: thanks for your support!
