### ISSUE TITLE
Plugin breaks when there is a item in SUMMARY using a Anchor link

### ISSUE THREAD

**Issue by hazenet** [todvora/gitbook-plugin-image-captions#17]
If there is a item in SUMMARY that is using a Anchor type link, the plugin breaks.
- [What is vRealize Orchestrator](what-is-vrealize-orchestrator.md)
  - [Origin](what-is-vrealize-orchestrator.md#origin)

Error seen:
`Error: ENOENT: no such file or directory, open '/tmp/book/what-is-vrealize-orchestrator.md#origin'`

**Comment by todvora** [comment]
Hi @hazenet,
Thanks for the information and example input. It should be fixed now in `3.0.2` version of the plugin. Please give it a try and let me know if everything works for you. I've also added [a test](https://github.com/todvora/gitbook-plugin-image-captions/blob/d3f9f58ef666b103690052f8da2911b7791be7dc/spec/tests_spec.js#L365) to prevent any similar issue in future. 

Best regards,
Tomas

**Comment by hazenet** [comment]
Works perfectly now, thanks for the quick fix.

**Comment by todvora** [comment]
I'm glad I could help. Thanks for testing it out!
