### ISSUE TITLE
Caption for video link

### ISSUE THREAD

**Issue by michaellwest** [todvora/gitbook-plugin-image-captions#4]
Thank you for publishing this great plugin. I have a scenario which I think previously worked.

Can you support something like this? Basically I need a thumbnail with a video link that opens in a new tab.

```
[![SPE Remoting Module](http://img.youtube.com/vi/fGvT8eDdWrg/0.jpg)](http://www.youtube.com/watch?v=fGvT8eDdWrg "Click for a quick demo")
```

![image](https://cloud.githubusercontent.com/assets/933163/12080659/ec871ee4-b226-11e5-9c4a-7c61ab8c6d3d.png)

**Comment by todvora** [comment]
Hi Michael,
Thank you for reporting this issue. You are right, it has been working earlier. It should be fixed now in the release `0.3.1`. You can try it using the latest release or force gitbook to use exactly `0.3.1` by defining this in your book.json:

``` json
{
    "plugins": ["image-captions@0.3.1" ]
}
```

Real working example of your code can be seen on https://tdvorak.gitbooks.io/test-book/content/phetchaburi.html

I used your example also in [tests](https://github.com/todvora/gitbook-plugin-image-captions/blob/76ab44619beb2ff958593ffb93dc4ca64f62a902/spec/tests_spec.js#L277) to prevent any similar bug in future. Is it ok for you?

Thanks,
Tomas

**Comment by michaellwest** [comment]
Hey that's great! Thank you for the quick turnaround. I'll test later by rebuilding my book.Feel free to use the example for your tests.

**Comment by michaellwest** [comment]
Back in action. Thanks!

**Comment by todvora** [comment]
:+1: Glad I could help
